name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100
    - name: Install dependencies
      run: dotnet restore Chemistry.NET/Chemistry.NET.csproj
    - name: Build
      run: dotnet build Chemistry.NET/Chemistry.NET.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test Chemistry.NET.Tests/Chemistry.NET.Tests.csproj --no-restore --verbosity normal
